{{ $data := dict }}

{{- with .Values.authzproxy.params.platformCABundle }}
{{ $_ := set $data "ca.crt" . }}
{{- end }}

{{- if $data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin.fullname" . }}-platform-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
type: Opaque
stringData: {{ $data | toJson }}
{{- end }}
